# Generated by Django 5.0.4 on 2024-06-11 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plano_terapeutico',
            old_name='dias_internado',
            new_name='sessoes_prescritas',
        ),
        migrations.RenameField(
            model_name='plano_terapeutico',
            old_name='numero_sessoes',
            new_name='sessoes_restantes',
        ),
        migrations.RemoveField(
            model_name='plano_terapeutico',
            name='paciente',
        ),
        migrations.AddField(
            model_name='paciente',
            name='plano_terapeutico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gestao.plano_terapeutico'),
        ),
    ]
