# Generated by Django 5.0.4 on 2024-05-23 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leito',
            name='ocupado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leito',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gestao.paciente'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='data_alta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='data_internacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='leito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gestao.leito'),
        ),
    ]
