# Generated by Django 5.0.4 on 2024-06-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao', '0002_alter_paciente_leito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estagio_atual',
            field=models.CharField(choices=[('CADASTRADO', 'Cadastrado'), ('PRESCRICAO_CRIADA', 'Prescricao Criada'), ('DEVOLVIDO_PELA_FARMACIA', 'Prescricao Devolvida Pela Farmacia'), ('DEVOLVIDO_PELA_REGULACAO', 'Prescricao Devolvida Pela Regulacao'), ('ENCAMINHADO_PARA_FARMACIA', 'Encaminhado Para Farmacia'), ('ENCAMINHADO_PARA_AGENDAMENTO', 'Encaminhado Para Agendamento'), ('AUTORIZADO_PARA_TRANSFERENCIA', 'Autorizado Para Transferencia'), ('TRANSFERIDO', 'Transferido'), ('AGENDADO', 'Agendado'), ('INTERNADO', 'Internado'), ('ALTA_OBITO', 'Alta Obito'), ('ALTA_NORMAL', 'Alta Normal'), ('ALTA_DEFINITIVA', 'Alta Definitiva')], default='CADASTRADO', max_length=128),
        ),
        migrations.AlterField(
            model_name='registro',
            name='estagio_atual',
            field=models.CharField(choices=[('CADASTRADO', 'Cadastrado'), ('PRESCRICAO_CRIADA', 'Prescricao Criada'), ('DEVOLVIDO_PELA_FARMACIA', 'Prescricao Devolvida Pela Farmacia'), ('DEVOLVIDO_PELA_REGULACAO', 'Prescricao Devolvida Pela Regulacao'), ('ENCAMINHADO_PARA_FARMACIA', 'Encaminhado Para Farmacia'), ('ENCAMINHADO_PARA_AGENDAMENTO', 'Encaminhado Para Agendamento'), ('AUTORIZADO_PARA_TRANSFERENCIA', 'Autorizado Para Transferencia'), ('TRANSFERIDO', 'Transferido'), ('AGENDADO', 'Agendado'), ('INTERNADO', 'Internado'), ('ALTA_OBITO', 'Alta Obito'), ('ALTA_NORMAL', 'Alta Normal'), ('ALTA_DEFINITIVA', 'Alta Definitiva')], editable=False, max_length=128),
        ),
    ]
