# Generated by Django 5.0.4 on 2024-06-12 01:54

import app_gestao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao', '0002_rename_dias_internado_plano_terapeutico_sessoes_prescritas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='criada_em',
            field=models.DateTimeField(default=app_gestao.models.Sessao.agora, editable=False),
        ),
    ]
