# Generated by Django 5.0.4 on 2024-06-19 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao', '0003_alter_paciente_estagio_atual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao.paciente'),
        ),
    ]
