# Generated by Django 5.0.4 on 2024-09-20 01:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao', '0005_alter_sessao_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessao',
            name='atualizada_em',
            field=models.DateField(auto_now=True),
        ),
    ]
